### ISSUE TITLE
Make an example

### ISSUE THREAD

**Issue by Nealium104** [bluegrass-devs/lextalk-tech#2]
As a team member, I'd like to be able to see an example of an issue and get a good idea of how Github Projects works.

Because this is a bigger task that might take some additional breaking down of tasks, I've made another individual project for it here:
https://github.com/orgs/bluegrass-devs/projects/3/views/1

**Comment by joekr** [comment]
Done as part of https://github.com/bluegrass-devs/lextalk-tech/pull/24
