### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by Nealium104** [bluegrass-devs/lextalk-tech#5]
As a user, I'd like an attractive landing page where I can get the general information about the conference and view a schedule of the latest conference.

Because this is a large amount of work, we've created a sub project for it here:

- [x]  Nav @Nealium104 
- [x] Footer @Nealium104 
- [ ] Speaker Section @Nealium104 
- [ ] Schedule Section
- [ ] Organizers @Nealium104

**Comment by emberborja** [comment]
- [ ] I will do this thing

**Comment by joekr** [comment]
Done as part of https://github.com/bluegrass-devs/lextalk-tech/pull/24
